# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=40)),
                ('size', models.BigIntegerField(default=0)),
                ('peers', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('download_rate', models.FloatField(default=0)),
                ('downloaded_size', models.BigIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'torrent_entries',
                'verbose_name_plural': 'torrents',
            },
        ),
    ]
