# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 12:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TorrentEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('hash_value', models.CharField(max_length=40)),
                ('progress', models.PositiveSmallIntegerField(default=0, null=True)),
                ('download_rate', models.FloatField(default=0, null=True)),
                ('file_size', models.BigIntegerField(default=0, null=True)),
                ('downloaded_size', models.BigIntegerField(default=0, null=True)),
                ('peers', models.PositiveSmallIntegerField(default=0, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('worker_pid', models.PositiveIntegerField(default=0, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='TorrentGlobalEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('hash_value', models.CharField(max_length=40)),
                ('progress', models.PositiveSmallIntegerField(default=0, null=True)),
                ('file_size', models.BigIntegerField(default=0, null=True)),
                ('downloaded_size', models.BigIntegerField(default=0, null=True)),
                ('peers', models.PositiveSmallIntegerField(default=0, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
